from __future__ import annotations

from enum import Enum
from typing import Any


KEYS = {
    "platform": "平台",
    "python": "运行环境版本",
    "cpu_count": "处理器核心数",
    "memory_gb": "内存GB",
    "gpu_available": "OCR可用显卡",
    "gpu": "显卡状态",
    "hardware_available": "检测到显卡硬件",
    "hardware_name": "显卡名称",
    "hardware_memory_gb": "显存GB",
    "driver_version": "驱动版本",
    "compute_capability": "显卡计算能力",
    "device_count": "显卡数量",
    "backend": "加速后端",
    "runtime_available": "OCR运行后端可用",
    "confirmed": "已确认图形处理器计算",
    "device": "实际运行设备",
    "reason": "判定说明",
    "recommended_mode": "推荐模式",
    "max_workers": "最大并发数",
    "max_dpi": "最高分辨率",
    "tools": "外部工具",
    "python_packages": "运行包",
    "readiness": "运行就绪度",
    "platform_supported": "系统受支持",
    "python_supported": "Python版本受支持",
    "runtime_dirs_writable": "运行目录可写",
    "uv_available": "可用uv",
    "recommended_runner": "推荐启动器",
    "notes": "说明",
    "name": "名称",
    "available": "可用",
    "version": "版本",
    "path": "路径",
    "page_number": "页码",
    "width": "宽度",
    "height": "高度",
    "text_chars": "文本字数",
    "text_blocks": "文本块数",
    "image_blocks": "图像块数",
    "xobject_images": "嵌入图像数",
    "image_coverage_ratio": "图像覆盖率",
    "garble_score": "乱码风险",
    "garble_risk": "乱码风险",
    "likely_scanned": "疑似扫描页",
    "likely_has_usable_text": "疑似可直接用文本",
    "warnings": "警告",
    "page_count": "总页数",
    "inspected_pages": "已检查页数",
    "pdf_type": "PDF类型",
    "has_extractable_text": "存在可抽取文本",
    "has_outline": "存在书签目录",
    "has_toc_like_pages": "发现目录页特征",
    "text_layer_quality": "文本层质量",
    "coverage_score": "文本覆盖率",
    "scanned_page_ratio": "扫描页比例",
    "text_page_ratio": "文本页比例",
    "recommended_action": "建议动作",
    "pages": "页面",
    "encrypted": "是否加密",
    "file_size_bytes": "文件大小字节",
    "pdf_version": "PDF格式版本",
    "chunk_id": "片段编号",
    "book_title": "书名",
    "chapter": "章节",
    "page_start": "起始页",
    "page_end": "结束页",
    "text": "文本",
    "confidence": "置信度",
    "source_page": "来源页",
    "source_path": "来源路径",
    "metadata": "元数据",
    "printed_page": "书内页码",
    "source": "来源",
    "blocks": "识别块",
    "ocr_device": "OCR设备",
    "gpu_confirmed": "已确认图形处理器计算",
    "status": "状态",
    "job_dir": "任务目录",
    "engine": "引擎",
    "manifest_path": "清单路径",
    "markdown_path": "正文路径",
    "chunks_path": "片段路径",
    "pages_path": "页面路径",
    "quality_path": "质量报告路径",
    "audit_path": "审计报告路径",
    "next_steps": "后续步骤",
    "route": "处理路线",
    "mode": "模式",
    "model_hint": "模型建议",
    "dpi": "分辨率",
    "estimated_seconds": "预计秒数",
    "runtime_recommended_mode": "设备推荐模式",
    "outputs": "输出",
    "source_pdf": "来源PDF",
}


VALUES = {
    "cpu": "处理器",
    "gpu": "图形处理器加速",
    "cuda": "图形处理器加速",
    "rocm": "图形处理器加速",
    "born_digital_full_text": "全量文本PDF",
    "searchable_scanned_pdf": "可搜索扫描PDF",
    "mixed_pdf": "混合PDF",
    "broken_text_layer_pdf": "损坏文本层PDF",
    "image_only_scanned_pdf": "纯扫描PDF",
    "empty_or_unknown_pdf": "空白或未知PDF",
    "password_protected_pdf": "密码保护PDF",
    "corrupted_pdf": "结构损坏PDF",
    "extract_directly_no_ocr": "直接抽取文本，不进行OCR",
    "reuse_text_layer_with_quality_audit": "复用现有文本层，并保留质量审计",
    "ocr_scanned_pages_only": "只识别扫描页",
    "strip_or_ignore_text_layer_and_rebuild_ocr": "忽略或剥离坏文本层后重建",
    "run_full_book_ocr": "整本书进行OCR",
    "manual_review_required": "需要人工复核",
    "password_required": "需要提供PDF密码",
    "repair_required": "需要先修复PDF",
    "book-fast": "书籍快速模式",
    "book-balanced": "书籍均衡模式",
    "book-balanced-low-memory": "书籍均衡低内存模式",
    "book-quality": "书籍高质量模式",
    "book-fast-low-memory": "书籍快速低内存模式",
    "book-forensic": "书籍取证级模式",
    "direct_text_extract": "直接抽取文本",
    "reuse_text_layer_with_audit": "复用文本层并审计",
    "ocr_required": "需要OCR识别",
    "pdf_text_layer": "PDF文本层",
    "existing_ocr_text_layer": "现有OCR文本层",
    "page_cache": "逐页缓存",
    "blank_page": "疑似空白页",
    "paddleocr": "飞桨OCR",
    "paddleocr_hybrid": "飞桨OCR与PDF文本层混合路线",
    "tesseract_hybrid": "备用OCR与PDF文本层混合路线",
    "paddle": "飞桨运行后端",
    "tesseract": "备用OCR",
    "ocrmypdf": "文本层修复工具",
    "ghostscript": "PDF底层处理工具",
    "qpdf": "PDF结构检查工具",
    "pdftoppm": "PDF转图片工具",
    "fitz": "PDF处理包",
    "pytesseract": "备用OCR运行包",
    "PIL": "图像处理包",
    "none": "无可用OCR引擎",
    "ok": "完成",
    "needs_ocr_engine": "需要安装OCR引擎",
    "needs_password": "需要提供PDF密码",
}


MESSAGES = {
    "not found on PATH": "未在系统路径中找到",
    "PaddleOCR is not installed; image-only PDFs will need OCR extras.": "未安装飞桨OCR；纯扫描PDF需要安装OCR扩展后才能识别。",
    "已安装飞桨OCR接口，但缺少飞桨运行后端。": "已安装飞桨OCR接口，但缺少飞桨运行后端。",
    "OCR引擎初始化失败；请检查飞桨运行后端和模型文件。": "OCR引擎初始化失败；请检查飞桨运行后端和模型文件。",
    "重新安装OCR扩展：uv sync --extra ocr": "重新安装OCR扩展：uv sync --extra ocr",
    "首次运行需要下载中文OCR模型，请保持网络可用。": "首次运行需要下载中文OCR模型，请保持网络可用。",
    "Tesseract command is not available; searchable PDF fallback is disabled.": "未检测到备用OCR命令；可搜索PDF修复备用通道不可用。",
    "OCRmyPDF command is not available; OCR text-layer repair is disabled.": "未检测到文本层修复工具；暂不能自动重建可搜索PDF文本层。",
    "possible broken or garbled text layer": "文本层可能损坏或乱码",
    "image-only scanned page": "纯图像扫描页",
    "scanned page with sparse text layer": "扫描页存在稀疏文本层",
    "empty PDF": "PDF为空",
    "many pages have a suspicious text layer": "多页文本层可疑",
    "document appears to mix native-text pages and scanned pages": "文档疑似混合了原生文本页和扫描页",
    "little text or image evidence was found": "可用文本或图像证据很少",
    "using existing OCR text layer; review quality report for scanned pages": "正在复用现有OCR文本层；请查看质量报告中的扫描页风险。",
    "no OCR engine is installed; only inspection artifacts were written": "未安装OCR引擎；本次只写入检查结果。",
    "Install OCR extras with: uv sync --extra ocr": "安装OCR扩展：uv sync --extra ocr",
    "Install PaddleOCR for Chinese book OCR.": "安装飞桨OCR以识别中文扫描书。",
    "Install Tesseract/OCRmyPDF if searchable PDF repair is needed.": "如需修复可搜索PDF文本层，请安装备用OCR与文本层修复工具。",
    "OCR returned no text": "OCR没有返回文本",
    "OCR is required but no OCR Python package is installed": "需要OCR识别，但未安装可用OCR运行包",
    "estimated runtime exceeds max_seconds; use fast mode or sample pages first": "预计耗时超过限制；建议先用快速模式或抽样页测试。",
    "No OCR model needed": "不需要OCR模型",
    "Install PaddleOCR for Chinese scanned books": "请安装飞桨OCR来处理中文扫描书",
    "Tesseract fallback; better for simple pages than complex Chinese books": "备用OCR更适合简单页面，不适合作为复杂中文书主力",
    "PP-OCRv6 small for balanced, medium for quality/forensic": "均衡模式用小型中文模型，高质量或取证级用中型中文模型",
}


def zh_value(value: Any) -> Any:
    if isinstance(value, Enum):
        value = value.value
    if isinstance(value, str):
        if value.startswith("inspection sampled ") and " pages" in value:
            parts = value.replace("inspection sampled ", "").replace(" pages", "")
            return f"本次抽样检查了 {parts} 页"
        return MESSAGES.get(value, VALUES.get(value, value))
    return value


def zh_data(value: Any) -> Any:
    if hasattr(value, "model_dump"):
        value = value.model_dump(mode="json")
    if isinstance(value, dict):
        return {
            KEYS.get(str(key), VALUES.get(str(key), str(key))): zh_data(zh_value(item))
            for key, item in value.items()
        }
    if isinstance(value, list):
        return [zh_data(zh_value(item)) for item in value]
    return zh_value(value)
